### ISSUE TITLE
Tab width not considered in alignment

### ISSUE THREAD

**Issue by PowerUser64** [RRethy/nvim-align#4]
When aligning text that has a tab at the start, `align` only considers the tab as one character. For example, given this text:

(imagine that the `t`'s are tabs)
```
12345678
Hello
tHello
ttHello
```

Selecting the text and running `:'<,'>Align Hello` will result in this output:

```
12345678
  Hello
t Hello
ttHello
```

When looking only at the characters, this is an okay result, but the way it is rendered is a different story:

```
12345678
  Hello
     Hello
        Hello
```

Since aligning is usually for visual purposes, it would probably be best to consider tabs to be the width of the current `tabstop` in order to produce a result like this:
```
12345678
        Hello
t    Hello
ttHello
```
So it renders like this:
```
12345678
        Hello
        Hello
        Hello
```

**Comment by RRethy** [comment]
Using tabstop would break the plugin for people not using tabs, and most use-cases in general. The root issue is mixing tabs and spaces, not how many spaces there are. There's not a great way to resolve this because any solution would break the plugin for people using spaces (even using expandtab wouldn't work, think trying to align things on the `=` of variable assignments).
